name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: build-test
    env:
      MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
      MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      MINIO_URL: ${{ secrets.MINIO_URL }}
      SHORTENER_API_KEY: ${{ secrets.SHORTENER_API_KEY }}
      SHORTENER_API_HOST: ${{ secrets.SHORTENER_API_HOST }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./server/

      - name: Build
        run: dotnet build --no-restore ./server/

      - name: Test
        run: dotnet test --no-build --verbosity normal ./server/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: net-build
          path: ./

  push-to-dockerhub:
    needs: build-test
    environment: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: net-build
          path: .

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/imagizer .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/imagizer
